### ISSUE TITLE
Calculation of scitype is too slow on Arrays

### ISSUE THREAD

**Issue by deepaksuresh** [alan-turing-institute/ScientificTypes.jl#28]
As of now, scitype for arrays are calculated as
```
scitype(A::B, ::Val) where {T,N,B<:AbstractArray{T,N}} =
    AbstractArray{scitype_union(A),N}
```
https://github.com/alan-turing-institute/ScientificTypes.jl/blob/21f3bcd8ba032a94586f684d8057629ef4719d0d/src/ScientificTypes.jl#L143-L144

where `scitype_union` is defined as
`scitype_union(A) = reduce((a,b)->Union{a,b}, (scitype(el) for el in A))`
https://github.com/alan-turing-institute/ScientificTypes.jl/blob/21f3bcd8ba032a94586f684d8057629ef4719d0d/src/ScientificTypes.jl#L133

This doesn't scale to large matrices. For instance, a matrix with 1 million rows and 1000 columns will have a billion elements in total. Calculating `scitype` or `scitype_union`  is going to be slow with the current definitions.

This can be bypassed if type information from base julia is made use of. For homogeneous matrices, all values in the matrix will be of the same datatype. Hence there is no need to run `scitype` on all elements. 

In case of an array of type `Array{Float32,2}`, the composite type can be defined as 
`scitype(X::Array{Float32,2})=AbstractArray{Continuous,2}`
The method `scitype_union` returns the same result.

This new definition has a remarkable impact on the performance of the method `machine` defined in [MLJ package](https://github.com/alan-turing-institute/MLJ.jl). The `machine` method relies on `scitype` to infer composite types. Hence this slows down `machine` method as well.

**Comment by tlienart** [comment]
Out of curiosity, I ran your suggestion:

```julia
X = zeros(1_000_000, 1_000); df = DataFrame(X);
@time scitype(df)
```

(so not even using the hot version)

this takes `2.3s` on my machine.

The second call takes `0.0067` seconds.

**Comment by deepaksuresh** [comment]
I was referring to the slowdown in this method `scitype_union(A) = reduce((a,b)->Union{a,b}, (scitype(el) for el in A)) `

**Comment by ablaom** [comment]
@deepaksuresh Thanks for your post.

In ScientificTypes 0.2.2 the scitype method for AbstractFloat and Integer arrays, and Categorical arrays, are all overloaded with performant versions (no scitype_union) https://github.com/alan-turing-institute/ScientificTypes.jl/pull/23. 

Note the reason one still needs the slow fallback is that there are cases where the eltype of an array does not determine the scientific type.  For example, if you have a `Vector{CategoricalString{UInt8}}` (rather than a `CategoricalVector{String, etc}`), you cannot tell if the elements have an ordered or unordered pool, or tell the number of classes, from the eltype alone. You need to look at the elements. 

If you discovered a persistent performance issue, please provide a WIP with timings? Otherwise,  please close, thanks.
